import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";

const Posts: NextPage = (props) => {

  return (
    <>
      <Head>
        <title>JameScape</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        
        <p className="text-2xl text-gray-700">Posts:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          {props.posts.map((p) => 
          <a href={`/posts/${p.id}`}>
            <TechnologyCard
              key={p.id}
              name={p.title}
              description={p.body}
              category={p.category}
            />
          </a>
          )}
        </div>
      </main>
    </>
  );
};

export default Posts;

type TechnologyCardProps = {
  name: string;
  description: string;
  category: string;
};

const TechnologyCard = ({
  name,
  description,
  category
}: TechnologyCardProps) => {
  return (
    <>
    <section>
      <div className="mx-auto flex w-full flex-col justify-center bg-base-100 rounded-2xl shadow-xl shadow-gray-400/20">
        <img className="aspect-video w-full rounded-t-2xl object-cover object-center" src="https://asset.vg247.com/OSRS_tombs_of_amascut.jpg/BROK/thumbnail/1600x900/quality/100/OSRS_tombs_of_amascut.jpg" />
        <div className="p-6">
          <small className=" text-green-600 text-xs">{category}</small>
          <h1 className="text-2xl font-medium text-gray-800 pb-2">{name}</h1>
          <p className="text text-gray-500 leading-6 truncate ...">{description}</p>
        </div>
      </div>
    </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await prisma.posts.findMany();
  return { props: { posts } }
}